version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: test/apache_stop.sh
      timeout: 10
      runas: root
  AfterInstall:
    - location: afterinstall.sh
      timeout: 10
      runas: root
  ApplicationStart:
    - location: apache_start.sh
      timeout: 10
      runas: root
